INF QcomPkg/XBLCore/XBLCore.inf

FILE FREEFORM = DDE58710-41CD-4306-DBFB-3FA90BB1D2DD {
    SECTION UI = "uefiplat.cfg"
    SECTION RAW = RawFiles/uefiplat.cfg
}

INF MdeModulePkg/Core/Dxe/DxeMain.inf
INF QcomPkg/Drivers/EnvDxe/EnvDxeEnhanced.inf
INF MdeModulePkg/Universal/ReportStatusCodeRouter/RuntimeDxe/RscRtDxe.inf
INF MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/SCHandlerRtDxe.inf
INF ArmPkg/Drivers/CpuDxe/CpuDxe.inf
INF MdeModulePkg/Core/RuntimeDxe/RuntimeDxe.inf
INF MdeModulePkg/Universal/SecurityStubDxe/SecurityStubDxe.inf
INF QcomPkg/Drivers/VerifiedBootDxe/VerifiedBootDxe.inf
INF QcomPkg/Drivers/ShmBridgeDxe/ShmBridgeDxeLA.inf
INF QcomPkg/Drivers/TzDxe/ScmDxeCompat.inf
INF QcomPkg/Drivers/TzDxe/TzDxeLA.inf
INF QcomPkg/Drivers/PsStateDxe/PsStateDxe.inf
INF MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer.inf
INF MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleRuntimeDxe.inf
INF QcomPkg/Drivers/VariableDxe/VariableDxe.inf
INF QcomPkg/Drivers/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf
INF QcomPkg/Drivers/ResetRuntimeDxe/ResetRuntimeDxe.inf
INF EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClockRuntimeDxe.inf
INF EmbeddedPkg/MetronomeDxe/MetronomeDxe.inf
INF MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf
INF QcomPkg/Drivers/QcomWDogDxe/QcomWDogDxe.inf
INF ArmPkg/Drivers/ArmGic/ArmGicDxe.inf
INF ArmPkg/Drivers/TimerDxe/TimerDxe.inf
INF QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
INF QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
INF QcomPkg/Drivers/ProjectInfoDxe/ProjectInfoDxe.inf
INF QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
INF QcomPkg/Drivers/HALIOMMUDxe/HALIOMMUDxe.inf
INF QcomPkg/Drivers/HWIODxe/HWIODxe.inf
INF QcomPkg/Drivers/HSUartDxe/HSUartDxe.inf
INF QcomPkg/Drivers/QupDxe/QupDxe.inf
INF QcomPkg/Drivers/GpiDxe/GpiDxe.inf
INF QcomPkg/Drivers/I2CDxe/I2CDxe.inf
INF QcomPkg/Drivers/ExFgDxe/ExFg.inf
INF QcomPkg/Drivers/I3CMasterDxe/I3CMasterDxe.inf
INF QcomPkg/Drivers/SPIDxe/SPIDxe.inf
INF QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
INF QcomPkg/Drivers/PmicDxe/PmicDxeLa.inf
INF MdeModulePkg/Universal/DevicePathDxe/DevicePathDxe.inf
INF MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIoDxe.inf
INF MdeModulePkg/Universal/Disk/PartitionDxe/PartitionDxe.inf
INF FatPkg/EnhancedFatDxe/Fat.inf
INF MdeModulePkg/Universal/Disk/UnicodeCollation/EnglishDxe/EnglishDxe.inf
INF MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemDxe.inf
INF QcomPkg/Drivers/UFSDxe/UFSDxe.inf
INF QcomPkg/Drivers/CmdDbDxe/CmdDbDxe.inf
INF QcomPkg/Drivers/PwrUtilsDxe/PwrUtilsDxe.inf
INF QcomPkg/Drivers/RpmhDxe/RpmhDxe.inf
INF QcomPkg/Drivers/NpaDxe/NpaDxe.inf
INF QcomPkg/Drivers/ULogDxe/ULogDxe.inf
INF QcomPkg/Drivers/MailboxDxe/MailboxDxe.inf
INF QcomPkg/Drivers/QcomScmiDxe/QcomScmiDxe.inf
INF QcomPkg/Drivers/CalibrationDxe/CalibrationDxe.inf
INF QcomPkg/Drivers/VcsDxe/VcsDxe.inf
INF QcomPkg/Drivers/ClockDxe/ClockDxe.inf
INF QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
INF QcomPkg/Drivers/ICBDxe/ICBDxe.inf
INF QcomPkg/Drivers/SmemDxe/SmemDxe.inf
INF QcomPkg/Drivers/QcomBds/QcomBds.inf
INF QcomPkg/Application/QcomChargerApp/QcomChargerAppGio.inf
INF QcomPkg/Drivers/RscDxe/RscDxe.inf

FILE FREEFORM = A91D838E-A5FA-4138-825D-455E2303079E {
    SECTION UI = "BDS_Menu.cfg"
    SECTION RAW = RawFiles/BDS_Menu.cfg
}


FILE FREEFORM = A1E235DE-E825-4591-9623-C43175811826 {
    SECTION UI = "SecParti.cfg"
    SECTION RAW = RawFiles/SecParti.cfg
}

INF QcomPkg/Application/Ebl/Ebl.inf
INF QcomPkg/Drivers/SimpleTextInOutSerialDxe/SimpleTextInOutSerial.inf
INF MdeModulePkg/Universal/PrintDxe/PrintDxe.inf
INF MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatformDxe.inf
INF MdeModulePkg/Universal/Console/ConSplitterDxe/ConSplitterDxe.inf
INF MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsoleDxe.inf
INF QcomPkg/Drivers/CPRDxe/CPRDxe.inf
INF QcomPkg/Drivers/AbSlotDxe/AbSlotDxe.inf
INF QcomPkg/Drivers/AndroidDxe/AndroidDxe.inf
INF QcomPkg/Drivers/SdccDxe/SdccDxe.inf
INF QcomPkg/Drivers/BootTimeDxe/BootTimeDxe.inf
INF QcomPkg/Drivers/RfChipDxe/RfChipDxe.inf
INF QcomPkg/Drivers/FeatureEnablerDxe/FeatureEnablerDxe.inf
INF QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf
INF QcomPkg/Drivers/QRKSDxe/QRKSDxe.inf
INF QcomPkg/Drivers/FMFDxe/FMFDxe.inf
INF QcomPkg/Drivers/ButtonsDxe/ButtonsDxe.inf
INF QcomPkg/Drivers/ChargerExDxe/ChargerExDxe.inf
INF QcomPkg/Drivers/IPCCDxe/IPCCDxe.inf
INF QcomPkg/Drivers/GLinkDxe/GLinkDxe.inf
INF QcomPkg/Drivers/PmicGlinkDxe/PmicGlinkSoccpDxe.inf
INF QcomPkg/Drivers/QcomChargerDxe/QcomChargerDxeLAGio.inf
INF QcomPkg/Drivers/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
INF QcomPkg/Drivers/TsensDxe/TsensDxe.inf
INF QcomPkg/Drivers/DDRInfoDxe/DDRInfoDxe.inf
INF QcomPkg/Drivers/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf
INF QcomPkg/Drivers/XhciPciEmulationDxe/XhciPciEmulationDxe.inf
INF QcomPkg/Drivers/XhciDxe/XhciDxe.inf
INF QcomPkg/Drivers/UsbBusDxe/UsbBusDxe.inf
INF QcomPkg/Drivers/UsbKbDxe/UsbKbDxe.inf
INF QcomPkg/Drivers/UsbMassStorageDxe/UsbMassStorageDxe.inf
INF QcomPkg/Drivers/UsbMsdDxe/UsbMsdDxe.inf
INF QcomPkg/Drivers/UsbDeviceDxe/UsbDeviceDxe.inf
INF QcomPkg/Drivers/UsbConfigDxe/UsbConfigDxe.inf
INF QcomPkg/Drivers/UsbInitDxe/UsbInitDxe.inf
INF QcomPkg/Drivers/UsbGblFastbootDxe/UsbGblFastbootDxe.inf
INF QcomPkg/Drivers/UCDxe/UCDxe.inf
INF QcomPkg/Drivers/RNGDxe/RngDxe.inf
INF QcomPkg/Drivers/PILDxe/PILDxe.inf
INF QcomPkg/Drivers/PILProxyDxe/PILProxyDxe.inf
INF QcomPkg/Drivers/SecRSADxe/SecRSADxe.inf
INF QcomPkg/Drivers/ASN1X509Dxe/ASN1X509Dxe.inf
INF QcomPkg/Drivers/SPSSDxe/SPSSDxe.inf
INF QcomPkg/Drivers/FvUtilsDxe/FvUtilsDxe.inf
INF QcomPkg/Drivers/RmVmDxe/RmVmDxe.inf
INF MiPkg/Protocol/MiToken/MiToken.inf
INF QcomPkg/Drivers/ParserDxe/ParserEnhancedDxe.inf

FILE FREEFORM = A91D838E-A5FA-4138-825D-455E23030794 {
    SECTION UI = "logo1.bmp"
    SECTION RAW = RawFiles/logo1.bmp
}


FILE FREEFORM = 8CAE2C55-FC5A-410B-812B-8CA22F572F36 {
    SECTION UI = "Panel_truly_wqxga_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_dsc_cmd.xml
}


FILE FREEFORM = 13AC9DC9-0092-4374-AE1A-06FF35950FD0 {
    SECTION UI = "Panel_truly_wqxga_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_dsc_vid.xml
}


FILE FREEFORM = FC6315F9-F8FE-4222-A1E3-226DF55D7592 {
    SECTION UI = "Panel_truly_wqxga_dual_cmd.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_dual_cmd.xml
}


FILE FREEFORM = 95E7B040-26A2-4511-9ABB-1D95D6DA7082 {
    SECTION UI = "Panel_truly_wqxga_dual_vid.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_dual_vid.xml
}


FILE FREEFORM = 8BC595B7-391A-4A9A-8256-5B9983B30392 {
    SECTION UI = "Panel_sharp_4k_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_sharp_4k_dsc_cmd.xml
}


FILE FREEFORM = 19B58ACD-B1F8-4078-B9A5-A33584B680E2 {
    SECTION UI = "Panel_sharp_4k_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_sharp_4k_dsc_vid.xml
}


FILE FREEFORM = 0AE323D6-2EBE-11E8-8349-9BA636A0D80C {
    SECTION UI = "Panel_sharp_1080p_cmd.xml"
    SECTION RAW = RawFiles/Panel_sharp_1080p_cmd.xml
}


FILE FREEFORM = 87273B42-311D-11E8-9324-DFB2DADFC3D1 {
    SECTION UI = "Panel_truly_1080p_cmd.xml"
    SECTION RAW = RawFiles/Panel_truly_1080p_cmd.xml
}


FILE FREEFORM = BAFD3200-311D-11E8-8651-0FB3CACF38FB {
    SECTION UI = "Panel_truly_1080p_vid.xml"
    SECTION RAW = RawFiles/Panel_truly_1080p_vid.xml
}


FILE FREEFORM = 88CA5ABF-D0AC-4093-A68C-0CFAE1EF9635 {
    SECTION UI = "Panel_boe_amoled_wqhd_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_boe_amoled_wqhd_dsc_cmd.xml
}


FILE FREEFORM = 6523A5C9-91CB-45C0-A2DC-25997CF23369 {
    SECTION UI = "Panel_boe_amoled_wqhd_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_boe_amoled_wqhd_dsc_vid.xml
}


FILE FREEFORM = D7170685-5965-4B44-9305-37CDB199B9BE {
    SECTION UI = "Panel_boe_amoled_fhd_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_boe_amoled_fhd_dsc_cmd.xml
}


FILE FREEFORM = 8F276EE4-E75E-4C3B-8BCC-C37771E26478 {
    SECTION UI = "Panel_nt36860_wqhd_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_nt36860_wqhd_dsc_cmd.xml
}


FILE FREEFORM = 6F2D4884-D8A0-11E9-AF7A-D77B1FE990EC {
    SECTION UI = "Panel_nt36860_wqhd_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_nt36860_wqhd_dsc_vid.xml
}


FILE FREEFORM = 81CE7295-491D-4E3F-AAA7-AB43FEF2F615 {
    SECTION UI = "Panel_r66451_60hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_r66451_60hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 8297C793-9861-422C-9F67-D447AF1EA812 {
    SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_r66451_120hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 61156380-EB8A-4618-940F-AB9BDEA1EEC2 {
    SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_cmd_hdk.xml"
    SECTION RAW = RawFiles/Panel_r66451_120hz_fhd_plus_dsc_cmd_hdk.xml
}


FILE FREEFORM = 44B09226-C2B4-45ED-AA6F-6686DB103978 {
    SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_r66451_120hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = D3F8580C-CCB8-4804-BB03-776E7B542FC2 {
    SECTION UI = "Panel_secondary_truly_1080p_cmd.xml"
    SECTION RAW = RawFiles/Panel_secondary_truly_1080p_cmd.xml
}


FILE FREEFORM = D192FEE9-6A04-4BE8-ABFE-5534E2B457EC {
    SECTION UI = "Panel_secondary_truly_1080p_vid.xml"
    SECTION RAW = RawFiles/Panel_secondary_truly_1080p_vid.xml
}


FILE FREEFORM = 9874B60A-6B80-4D76-8EEB-7862C780EC03 {
    SECTION UI = "Panel_r66451_144hz_fhd_plus_dsc_cmd_cphy.xml"
    SECTION RAW = RawFiles/Panel_r66451_144hz_fhd_plus_dsc_cmd_cphy.xml
}


FILE FREEFORM = BC28E12E-C7E0-47F9-BBF9-0B45ED6F4B18 {
    SECTION UI = "Panel_r66451_144hz_fhd_plus_dsc_vid_cphy.xml"
    SECTION RAW = RawFiles/Panel_r66451_144hz_fhd_plus_dsc_vid_cphy.xml
}


FILE FREEFORM = 637AD94D-7D9B-4D5F-B420-770B65BECDA8 {
    SECTION UI = "Panel_r66451_60hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_r66451_60hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = AE3F9548-010C-4AEC-A9D2-4AE3E16D2F8B {
    SECTION UI = "Panel_vtdr6130_144hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_144hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 12372575-2A07-4C4E-BE92-6093A55FED33 {
    SECTION UI = "Panel_vtdr6130_144hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_144hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = 36630E03-0236-4983-ABDE-F982B23419FE {
    SECTION UI = "Panel_vtdr6130_60hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_60hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 573FA171-1D5C-4C12-BDC8-19DCEFBBD483 {
    SECTION UI = "Panel_vtdr6130_60hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_60hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = 0A60AF27-D18D-452F-BB8B-1A886F7F6CCC {
    SECTION UI = "Panel_sharp_120hz_qhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_sharp_120hz_qhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 81466938-BB9E-43DC-A208-A41BA82A5861 {
    SECTION UI = "Panel_sharp_120hz_qhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_sharp_120hz_qhd_plus_dsc_vid.xml
}


FILE FREEFORM = 23EB5E2D-4A4D-4B35-BB7B-BE39D7EE440D {
    SECTION UI = "Panel_secondary_vtdr6130_144hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_secondary_vtdr6130_144hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = A413F4E1-50FE-4848-82F1-EFB814608221 {
    SECTION UI = "Panel_secondary_vtdr6130_144hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_secondary_vtdr6130_144hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = EB0A97F6-39DB-41D4-9B3C-CA3BADC144B4 {
    SECTION UI = "Panel_truly_wqxga_cmd_splitlink.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_cmd_splitlink.xml
}


FILE FREEFORM = F4A245C8-940E-4523-A53B-82E3C8BC6970 {
    SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_cmd_demura.xml"
    SECTION RAW = RawFiles/Panel_r66451_120hz_fhd_plus_dsc_cmd_demura.xml
}


FILE FREEFORM = 3DE03011-41E8-4353-A4E5-02721E71A0F4 {
    SECTION UI = "Panel_vtdr6130_144hz_fhd_plus_dsc_cmd_demura.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_144hz_fhd_plus_dsc_cmd_demura.xml
}


FILE FREEFORM = 0EF4D970-0B59-4AF4-A8F7-F6A239EED792 {
    SECTION UI = "Panel_vtdr6130_144hz_fhd_plus_dsc_cmd_rfi.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_144hz_fhd_plus_dsc_cmd_rfi.xml
}


FILE FREEFORM = 95FA1AB2-A4C8-4891-ABD3-3DE4BAB07680 {
    SECTION UI = "Panel_rumi_cwb_vga_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_rumi_cwb_vga_dsc_vid.xml
}


FILE FREEFORM = 138816EF-44B3-4FA1-9F8C-CA23B0AC72CD {
    SECTION UI = "Panel_vtdr6130_120hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_120hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 54603FD1-6CD3-469E-A2FB-D0759525C423 {
    SECTION UI = "Panel_vtdr6130_120hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_120hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = 564F33FA-E572-4678-A575-AF6AC20ED2BD {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 939DFDDF-82A2-459D-9E28-A38719B059B5 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd_cphy.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd_cphy.xml
}


FILE FREEFORM = 3D2431EB-AD6D-4753-B13C-26D4E7789A2E {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid.xml
}


FILE FREEFORM = 059BCC95-F398-411D-950D-02FD9F224755 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid_cphy.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid_cphy.xml
}


FILE FREEFORM = 019F1D56-BF74-49A3-9918-0E8125E101D2 {
    SECTION UI = "Panel_sec_nt37801_120hz_wqhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_sec_nt37801_120hz_wqhd_plus_dsc_cmd.xml
}


FILE FREEFORM = F019FF29-21E0-40C9-A93D-E13037A5E998 {
    SECTION UI = "Panel_sec_nt37801_120hz_wqhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_sec_nt37801_120hz_wqhd_plus_dsc_vid.xml
}


FILE FREEFORM = 67A9E045-A85A-4FDC-8AB6-3BB515F9F1E7 {
    SECTION UI = "Panel_nt37801_10bit_wqhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_nt37801_10bit_wqhd_plus_dsc_vid.xml
}


FILE FREEFORM = 7CFCD59F-3C6C-44D1-88F7-C84FF7457B7F {
    SECTION UI = "Panel_nt37801_10bit_wqhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_nt37801_10bit_wqhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 1B968D68-BD92-41F6-8529-EF1020A2003E {
    SECTION UI = "Panel_nt37801_120hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 5404E828-36D2-46C8-980F-CB74E505718A {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd_spr.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd_spr.xml
}


FILE FREEFORM = 0E21C2B3-F417-4AC8-891F-12BBFAA96FE6 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd_demura.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd_demura.xml
}


FILE FREEFORM = 52C03F36-4308-4DC5-8AC6-651120F23856 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid_spr.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid_spr.xml
}


FILE FREEFORM = 1A652C6C-24B6-451E-B8D5-D50A735F8442 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid_demura.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid_demura.xml
}


FILE FREEFORM = 2CED8194-4AE6-492E-8F68-E2D2D695688D {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd_cphy_demura.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd_cphy_demura.xml
}


FILE FREEFORM = C9B533B5-A619-4797-912D-8B93A9A026B5 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid_cphy_demura.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid_cphy_demura.xml
}


FILE FREEFORM = FD90858A-DA7E-4A5C-B2AB-4622DB7EFA63 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd_demura_nspr.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd_demura_nspr.xml
}


FILE FREEFORM = C37F9620-E4D0-4821-92E5-B5013B9D3EB7 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid_demura_nspr.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid_demura_nspr.xml
}


FILE FREEFORM = 035B1D20-1829-46EA-87D7-0A02C49E000E {
    SECTION UI = "Panel_sec_vtdr6130_144hz_fhd_plus_dsc_vid_rfi.xml"
    SECTION RAW = RawFiles/Panel_sec_vtdr6130_144hz_fhd_plus_dsc_vid_rfi.xml
}


FILE FREEFORM = 28A1E1E3-26D1-4413-9EC2-7F507847D119 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid_cphy_spr.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid_cphy_spr.xml
}


FILE FREEFORM = FAA15BC9-99BC-40B7-A423-58690009DF2E {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd_cphy_spr.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd_cphy_spr.xml
}


FILE FREEFORM = 0763B85C-45E3-4966-B1FD-D3D053C85A95 {
    SECTION UI = "Panel_sec_vtdr6130_144hz_fhd_plus_dsc_cmd_rfi.xml"
    SECTION RAW = RawFiles/Panel_sec_vtdr6130_144hz_fhd_plus_dsc_cmd_rfi.xml
}


FILE FREEFORM = 2ECFB0AF-93AF-4A3B-B420-43D46F77DF55 {
    SECTION UI = "Panel_Samsung_Esync.xml"
    SECTION RAW = RawFiles/Panel_Samsung_Esync.xml
}


FILE FREEFORM = 81D00687-181B-4B23-A1CC-85FE6B9E25E6 {
    SECTION UI = "Panel_sharp_120hz_qhdpipe_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_sharp_120hz_qhdpipe_plus_dsc_vid.xml
}


FILE FREEFORM = 7EA75A5E-2530-402E-993C-3052AD8F1863 {
    SECTION UI = "Panel_nt37802_120hz_vhm_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_nt37802_120hz_vhm_dsc_vid.xml
}


FILE FREEFORM = D2DE51EA-F5EA-481D-97AB-1FDBF2858803 {
    SECTION UI = "Panel_Samsung_Esync_Mrr.xml"
    SECTION RAW = RawFiles/Panel_Samsung_Esync_Mrr.xml
}


FILE FREEFORM = 03E9256F-E621-48D8-8576-7E3B4FCF2D41 {
    SECTION UI = "PanelSimConfig.csv"
    SECTION RAW = RawFiles/PanelSimConfig.csv
}


FILE FREEFORM = 7B066083-C2D3-4480-8396-3F3CC3034842 {
    SECTION UI = "Panel_P3_42_02_0a_p10_ltpo_dsc_vhm.xml"
    SECTION RAW = RawFiles/Panel_P3_42_02_0a_p10_ltpo_dsc_vhm.xml
}


FILE FREEFORM = ABADE0FF-65ED-41B7-959C-82902BB24727 {
    SECTION UI = "Panel_P3_42_02_0a_p11_ltpo_dsc_vhm.xml"
    SECTION RAW = RawFiles/Panel_P3_42_02_0a_p11_ltpo_dsc_vhm.xml
}


FILE FREEFORM = CDCEC1CA-21AC-32C1-124A-26125AC19215 {
    SECTION UI = "Panel_P3_42_02_0a_p12_ltpo_dsc_vhm.xml"
    SECTION RAW = RawFiles/Panel_P3_42_02_0a_p12_ltpo_dsc_vhm.xml
}


FILE FREEFORM = 481CE728-7B5E-4B6A-ABC4-D604202371E0 {
    SECTION UI = "Panel_P3_42_02_0a_p12_2_ltpo_dsc_vhm.xml"
    SECTION RAW = RawFiles/Panel_P3_42_02_0a_p12_2_ltpo_dsc_vhm.xml
}


FILE FREEFORM = E9C61163-E7BD-41F5-B175-FDA5410F7E34 {
    SECTION UI = "Panel_P3_42_02_0a_p20_ltpo_dsc_vhm.xml"
    SECTION RAW = RawFiles/Panel_P3_42_02_0a_p20_ltpo_dsc_vhm.xml
}


FILE FREEFORM = 38043A7E-1840-4452-B94F-23FADF787B73 {
    SECTION UI = "Panel_P3_42_02_0a_p21_ltpo_dsc_vhm.xml"
    SECTION RAW = RawFiles/Panel_P3_42_02_0a_p21_ltpo_dsc_vhm.xml
}


FILE FREEFORM = 2C923161-A8B2-5733-1625-1C3BA7142616 {
    SECTION UI = "Panel_P3_42_02_0a_ltpo_dsc_vhm.xml"
    SECTION RAW = RawFiles/Panel_P3_42_02_0a_ltpo_dsc_vhm.xml
}


FILE FREEFORM = 3B8F9F0C-7609-490C-9F7D-3CB85928DA11 {
    SECTION UI = "Panel_P3_36_02_0b_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P3_36_02_0b_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 60ECE386-7570-4CAD-85FE-FD3CEB514E7E {
    SECTION UI = "Panel_P3_42_02_0a_mp_ltpo_dsc_vhm.xml"
    SECTION RAW = RawFiles/Panel_P3_42_02_0a_mp_ltpo_dsc_vhm.xml
}


FILE FREEFORM = 17144781-B74C-4245-8127-F47EFF60D0CB {
    SECTION UI = "sprconfig_p3_42_02_0a_dsc_vhm.xml"
    SECTION RAW = RawFiles/sprconfig_p3_42_02_0a_dsc_vhm.xml
}


FILE FREEFORM = A0F8CFBC-71FC-45BC-AA63-4D50E170EB8D {
    SECTION UI = "sprconfig_p3_42_02_0a_mp_dsc_vhm.xml"
    SECTION RAW = RawFiles/sprconfig_p3_42_02_0a_mp_dsc_vhm.xml
}


FILE FREEFORM = A2CFA2DB-A85C-43AD-BCB4-6CD4D8EB72D8 {
    SECTION UI = "Panel_P3_42_02_0a_ltpo_dsc_vhm_pmic_b.xml"
    SECTION RAW = RawFiles/Panel_P3_42_02_0a_ltpo_dsc_vhm_pmic_b.xml
}


FILE FREEFORM = 1A7A3498-010E-4865-9C74-2E3FEFE15268 {
    SECTION UI = "sprconfig_q200_42_02_0a_mp_prim_dsc_cmd.xml"
    SECTION RAW = RawFiles/sprconfig_q200_42_02_0a_mp_prim_dsc_cmd.xml
}


FILE FREEFORM = 3C41B734-B9BA-4B49-A618-36BC1CDE6F75 {
    SECTION UI = "Panel_Q200_42_02_0a_p11_prim_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_Q200_42_02_0a_p11_prim_ltpo_dsc_cmd.xml
}


FILE FREEFORM = E01DF343-6363-4BB3-AB47-23CA3E690E46 {
    SECTION UI = "Panel_Q200_42_02_0a_p12_prim_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_Q200_42_02_0a_p12_prim_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 4F96B13B-A8B8-4E5C-969B-98AF6DA6C229 {
    SECTION UI = "Panel_Q200_42_02_0a_p12_2_prim_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_Q200_42_02_0a_p12_2_prim_ltpo_dsc_cmd.xml
}


FILE FREEFORM = CF077E13-5828-418A-8248-E5DCF8D124A4 {
    SECTION UI = "Panel_Q200_42_02_0a_p20_prim_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_Q200_42_02_0a_p20_prim_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 8004BDCA-7011-42CC-AC20-BD9D71FBDC9E {
    SECTION UI = "Panel_Q200_42_02_0a_p21_prim_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_Q200_42_02_0a_p21_prim_ltpo_dsc_cmd.xml
}


FILE FREEFORM = C77BE8EF-2E45-48F6-B3B2-2EB9CDACD9B5 {
    SECTION UI = "Panel_Q200_42_02_0a_mp_prim_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_Q200_42_02_0a_mp_prim_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 3DD1276A-1A58-468D-A82C-1E7C90ECE62B {
    SECTION UI = "Panel_P2_42_02_0a_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P2_42_02_0a_ltpo_dsc_cmd.xml
}


FILE FREEFORM = BECF60A8-356E-11F0-AAD7-03EAE3B06F05 {
    SECTION UI = "Panel_P2_42_02_0a_p11_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P2_42_02_0a_p11_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 07527848-4D0B-11F0-94D4-3BEB7F81C8B1 {
    SECTION UI = "Panel_P2_42_02_0a_p12_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P2_42_02_0a_p12_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 10D29084-5CAA-11F0-93BD-379A59C8481A {
    SECTION UI = "Panel_P2_42_02_0a_p2_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P2_42_02_0a_p2_ltpo_dsc_cmd.xml
}


FILE FREEFORM = C40DFFCA-3172-11F0-B445-2711B7126106 {
    SECTION UI = "Panel_P2_42_0D_0b_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P2_42_0D_0b_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 81C8688E-50D6-11F0-99ED-A34D272CE30D {
    SECTION UI = "Panel_P2_42_0D_0b_p12_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P2_42_0D_0b_p12_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 80AE094B-B2B9-4266-9A16-9B884D9BA435 {
    SECTION UI = "Panel_P2_42_0D_0b_p2_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P2_42_0D_0b_p2_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 9136A67A-889A-4CC4-BF54-AE72045DBAD0 {
    SECTION UI = "Panel_P2_42_06_0a_ltpo_dsc_cmd_sec.xml"
    SECTION RAW = RawFiles/Panel_P2_42_06_0a_ltpo_dsc_cmd_sec.xml
}


FILE FREEFORM = A6ED4CF1-BECB-40EF-AECF-2A0AD1A9B6D4 {
    SECTION UI = "Panel_Q200_42_06_0a_sec_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_Q200_42_06_0a_sec_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 9B379057-6111-4E09-A35E-CC366A3834B4 {
    SECTION UI = "Panel_P11U_42_0d_0a_p00_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P11U_42_0d_0a_p00_dsc_cmd.xml
}


FILE FREEFORM = EC20C99B-165E-4331-A1E7-B95954C2DB4D {
    SECTION UI = "Panel_P11U_42_0d_0a_p01_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P11U_42_0d_0a_p01_dsc_cmd.xml
}


FILE FREEFORM = 87BD48C7-DA5D-3198-4432-64AB90C94E58 {
    SECTION UI = "Panel_P11U_42_0d_0a_p1_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P11U_42_0d_0a_p1_dsc_cmd.xml
}


FILE FREEFORM = 3D903B36-E824-284D-EDCB-C3D4C9E5FA62 {
    SECTION UI = "Panel_P11U_42_0d_0a_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P11U_42_0d_0a_dsc_cmd.xml
}


FILE FREEFORM = 7A1480C7-5BEC-4DF7-A35B-CCD4CFC14504 {
    SECTION UI = "Panel_P1_42_02_0a_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P1_42_02_0a_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 8A49FC8D-80FD-48D3-9003-BE959F8B14D7 {
    SECTION UI = "Panel_P1_42_02_0a_p10_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P1_42_02_0a_p10_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 7F131DE0-3F70-4BB4-B6CA-C203A114B637 {
    SECTION UI = "Panel_P1_42_02_0a_p11_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P1_42_02_0a_p11_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 454A4F04-5722-4E7F-92CA-426A155D8F00 {
    SECTION UI = "Panel_4001_41_02_0a_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_4001_41_02_0a_ltpo_dsc_cmd.xml
}


FILE FREEFORM = F8867A0A-72A5-4A80-91AE-F07ACE3EFDBF {
    SECTION UI = "Panel_P1_42_0D_0b_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P1_42_0D_0b_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 53F4E9F3-A83B-4C34-A680-E218E860AE84 {
    SECTION UI = "Panel_P1_42_0D_0b_p10_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P1_42_0D_0b_p10_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 7025E58F-CD65-4522-BE48-D352DA3C4F4E {
    SECTION UI = "Panel_P1_42_0D_0b_p11_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P1_42_0D_0b_p11_ltpo_dsc_cmd.xml
}


FILE FREEFORM = CB4EF5C0-33CB-4256-8710-5C693B72B746 {
    SECTION UI = "Panel_P1_42_0D_0b_p12_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P1_42_0D_0b_p12_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 9A63D467-99EC-47E3-9636-96FAEAC4ADE3 {
    SECTION UI = "Panel_P8_42_02_0a_prim_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P8_42_02_0a_prim_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 57F82EC2-4B83-451A-B7EB-9B5D1040CACD {
    SECTION UI = "Panel_P8_42_02_0a_sec_ltpo_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_P8_42_02_0a_sec_ltpo_dsc_cmd.xml
}


FILE FREEFORM = 21E9BDD9-6C3F-4F10-84A5-BBEC322741F1 {
    SECTION UI = "uefipil.cfg"
    SECTION RAW = RawFiles/uefipil.cfg
}

INF QcomPkg/Application/Ebl/Ebl.inf
