name: Build myron UEFI

on:
  workflow_dispatch:
    inputs:
      build_mode:
        description: 'Build mode (DEBUG or RELEASE)'
        required: true
        default: 'DEBUG'
        type: choice
        options:
          - DEBUG
          - RELEASE

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y pip git build-essential uuid-dev nasm gcc-aarch64-linux-gnu python3 python3-pip gettext gnupg ca-certificates clang llvm curl lld
          python3 -m pip install -r pip-requirements.txt

      - name: Build UEFI for myron
        run: |
          python3 build_uefi.py -d myron -r ${{ inputs.build_mode || 'DEBUG' }}

      - name: Upload UEFI image
        uses: actions/upload-artifact@v7
        with:
          name: myron-uefi-${{ inputs.build_mode || 'DEBUG' }}
          path: |
            ./Mu-myron-*
            ./Build/myronPkg/*/FV/SILICIUM_UEFI.fd
          compression-level: 9
